version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - 'C:/Users/user/Desktop/devtalles/nest/pokedex/mongo:/data/db:rw'

